### PR TITLE
Add ojselectcombobox to switch between chart types.

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by geertjanw** [comment]
Created this because people in HOL in Slovenia asked how to do this and maybe would be good to have it in the final app, without necessarily including it step by step in the HOL instructions.

**Comment by peppertech** [comment]
This makes sense. I'll review the pr and merge

**Comment by geertjanw** [comment]
Nice!

**Comment by alanarentsen** [comment]
Ah great!
In Croatia the same. I added another feature but haven't checked it in.
A method on the CCA to set the chart type from JavaScript.

I'm on the way back to the Netherlands now. Will check it when I'm back

Cheers

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Pull request merged**
